In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


### Simulation

How likely is it that you roll doubles when rolling two dice?



In [2]:
n_trials = nrows = 10_000
n_dice = ncols = 2

rolls = np.random.choice([1,2,3,4,5,6], n_trials * n_dice).reshape(nrows,ncols)
rolls

array([[4, 5],
       [4, 3],
       [1, 1],
       ...,
       [1, 1],
       [4, 2],
       [4, 5]])

In [3]:
rolls = pd.DataFrame(rolls)
print(f'{(rolls[0] == rolls[1]).mean()}% chance to roll doubles')

0.1669% chance to roll doubles


If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?



In [4]:
# making life easier(?) heads = 1, tails = 0
c_trials = crows = 10_000
c_dice = ccols = 8

coins = np.random.choice([1,0], c_trials * c_dice).reshape(crows,ccols)
coins

array([[0, 0, 1, ..., 0, 1, 1],
       [1, 0, 0, ..., 0, 1, 0],
       [1, 0, 0, ..., 1, 1, 0],
       ...,
       [1, 1, 1, ..., 1, 1, 0],
       [1, 1, 1, ..., 0, 1, 1],
       [1, 0, 0, ..., 0, 0, 1]])

In [5]:
coins = pd.DataFrame(coins)
sum_of_flips = coins.sum(axis=1)
exactly_three_heads = sum_of_flips == 3
more_than_three_heads = sum_of_flips > 3
all_heads = sum_of_flips == 8
all_tails = sum_of_flips == 0
rate_of_3_heads = exactly_three_heads.astype(int).mean()
rate_of_more_than_3 = more_than_three_heads.astype(int).mean()
rate_all_heads = all_heads.astype(int).mean()
rate_all_tails = all_tails.astype(int).mean()
print(f'{rate_of_3_heads} chance of exactly 3 heads, {rate_of_more_than_3} chance of more than 3 heads.')
print(f"There's also a {rate_all_heads} chance of all heads, and {rate_all_tails} chance of all tails.")

0.2156 chance of exactly 3 heads, 0.6338 chance of more than 3 heads.
There's also a 0.0043 chance of all heads, and 0.003 chance of all tails.


There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?



In [6]:
outcomes = ['web', 'web', 'web', 'ds']
billboards_tot = 2
billboards = np.random.choice(outcomes, size = (n_trials, billboards_tot))
billboards

array([['web', 'ds'],
       ['ds', 'web'],
       ['web', 'web'],
       ...,
       ['web', 'web'],
       ['web', 'web'],
       ['web', 'ds']], dtype='<U3')

In [7]:
((billboards == 'ds').sum(axis=1) == 2).mean()

0.0626

Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal) You'll need to make a judgement call on how to handle some of your values



In [9]:
mean = 3
sd = 1.5
days = 5

poptarts_a_day = np.random.normal(mean, sd, size=(n_trials, days))
poptarts_a_day

array([[ 2.55083996,  1.24205928,  4.13011281,  1.28939135,  3.83300038],
       [ 4.53772555,  5.44259194,  2.70415891,  4.5920272 ,  4.03919968],
       [ 7.50892937,  4.43283699,  3.27138954,  3.93152674,  1.76796025],
       ...,
       [ 2.39529715,  1.60945646,  2.41659897,  3.0786127 ,  5.11391096],
       [ 3.51032572,  1.14632785,  2.57819891,  2.7154981 ,  2.48824373],
       [ 0.69410191,  4.3398688 ,  0.74374805,  2.87618303, -0.55646581]])

In [11]:
poptarts_a_week = poptarts_a_day.sum(axis=1)

0

In [12]:
print(f"{(poptarts_a_week < 17).mean()} chance to be able to purchase a poptart on Friday afternoon.")

0.7167 chance to be able to purchase a poptart on Friday afternoon.


Compare Heights

Men have an average height of 178 cm and standard deviation of 8cm.
Women have a mean of 170, sd = 6cm.
Since you have means and standard deviations, you can use np.random.normal to generate observations.
If a man and woman are chosen at random, what is the likelihood the woman is taller than the man?


In [13]:
male_mean = 178
male_sd = 8
female_mean = 170
female_sd = 6

In [15]:
male_height = np.random.normal(male_mean, male_sd, n_trials)
male_height

array([161.23707639, 167.12150181, 178.32664999, ..., 182.82792861,
       183.63727623, 176.45900636])

In [16]:
female_height = np.random.normal(female_mean, female_sd,n_trials)
female_height

array([172.86993059, 166.58819607, 174.16201087, ..., 172.88520675,
       170.05306409, 165.76174556])

In [17]:
(female_height > male_height).mean()

0.2131

When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

What is the probability that we observe an installation issue within the first 150 students that download anaconda?

How likely is it that 450 students all download anaconda without an issue?



In [20]:
install_outcomes = ['S', 'F']
students = 50
downloads = np.random.choice(install_outcomes, size=(n_trials, students), p = [249/250, 1/250])
downloads

array([['S', 'S', 'S', ..., 'S', 'S', 'S'],
       ['S', 'S', 'S', ..., 'S', 'S', 'S'],
       ['S', 'S', 'S', ..., 'S', 'S', 'S'],
       ...,
       ['S', 'S', 'S', ..., 'S', 'S', 'S'],
       ['S', 'S', 'S', ..., 'S', 'S', 'S'],
       ['S', 'S', 'S', ..., 'S', 'S', 'S']], dtype='<U1')

In [21]:
((downloads == 'S').sum(axis=1) == 50).mean()

0.8204

In [22]:
students2 = 100
downloads = np.random.choice(install_outcomes, size=(n_trials, students2), p = [249/250, 1/250])
downloads

array([['S', 'S', 'S', ..., 'S', 'S', 'S'],
       ['S', 'S', 'S', ..., 'S', 'S', 'S'],
       ['S', 'S', 'S', ..., 'S', 'S', 'S'],
       ...,
       ['S', 'S', 'S', ..., 'S', 'S', 'S'],
       ['S', 'S', 'S', ..., 'S', 'S', 'S'],
       ['S', 'S', 'S', ..., 'S', 'S', 'S']], dtype='<U1')

In [24]:
((downloads == 'S').sum(axis=1) == 100).mean()

0.6705

In [25]:
students3 = 150
downloads = np.random.choice(install_outcomes, size=(n_trials, students3), p = [249/250, 1/250])
downloads

array([['S', 'S', 'S', ..., 'S', 'S', 'S'],
       ['S', 'S', 'S', ..., 'S', 'S', 'S'],
       ['S', 'S', 'S', ..., 'S', 'S', 'S'],
       ...,
       ['S', 'S', 'S', ..., 'S', 'S', 'S'],
       ['S', 'S', 'S', ..., 'S', 'S', 'S'],
       ['S', 'S', 'S', ..., 'S', 'S', 'S']], dtype='<U1')

In [26]:
((downloads == 'S').sum(axis=1) < students3).mean()

0.4608

In [27]:
students4 = 450
downloads = np.random.choice(install_outcomes, size=(n_trials, students4), p = [249/250, 1/250])
downloads

array([['S', 'S', 'S', ..., 'S', 'S', 'S'],
       ['S', 'S', 'S', ..., 'S', 'S', 'S'],
       ['S', 'S', 'S', ..., 'S', 'S', 'S'],
       ...,
       ['S', 'S', 'S', ..., 'S', 'S', 'S'],
       ['S', 'S', 'S', ..., 'S', 'S', 'S'],
       ['S', 'S', 'S', ..., 'S', 'S', 'S']], dtype='<U1')

In [28]:
((downloads == 'S').sum(axis=1) == students4).mean()

0.1665

There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

How likely is it that a food truck will show up sometime this week?



In [31]:
food_truck_prob = 0.70
days = 3
is_truck_here = np.random.random((n_trials, days))
is_truck_here

array([[0.33056647, 0.92158573, 0.56702308],
       [0.72009811, 0.83907307, 0.05934625],
       [0.17606929, 0.59704233, 0.57635545],
       ...,
       [0.92576837, 0.07569321, 0.8950645 ],
       [0.50349566, 0.50933209, 0.65549029],
       [0.26687792, 0.90625187, 0.67470713]])

In [32]:
food_is_here = (is_truck_here < food_truck_prob)
food_is_here

array([[ True, False,  True],
       [False, False,  True],
       [ True,  True,  True],
       ...,
       [False,  True, False],
       [ True,  True,  True],
       [ True, False,  True]])

In [33]:
(food_is_here.sum(axis=1) == 0).mean()

0.0268

In [34]:
days = 7
is_truck_here = np.random.random((n_trials, days))
food_is_here = (is_truck_here < food_truck_prob)
(food_is_here.sum(axis=1) > 0).mean()

0.9996

If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?



In [48]:
outcome = range(366)
people = 23

birthdays = np.random.choice(outcome, size=(n_trials,people))
birthdays

array([[264,  76,   6, ...,  40,  22, 109],
       [267, 136,  23, ..., 310, 126, 293],
       [105,  66, 183, ..., 144,  14, 105],
       ...,
       [354, 291, 323, ..., 248, 142, 176],
       [259, 309, 324, ...,  38, 149,  82],
       [ 37, 205,  86, ...,  59,  57, 288]])

In [49]:
birthdays = pd.DataFrame(birthdays)
birthdays

0    1    2    3    4    5    6    7    8    9   ...   13   14   15  \
0     264   76    6   39  361  185  278  239   79  143  ...  245  276  354   
1     267  136   23   95   60  345   81  323   11   85  ...   25  267    9   
2     105   66  183  319  134  101  165   14  152  302  ...  192  320   62   
3     263  117  111   91  352  275  131  324  281  132  ...   84  277    3   
4     168  177   73   12  148   17  185  113  260  332  ...  295  151   33   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
9995  127   69  322  321   89  182  108  161   50  252  ...   60  293  317   
9996   84  127  353  122  190  353    4  354   81  151  ...   88  286   54   
9997  354  291  323  276  326   55   46   48  141  169  ...   67  317   71   
9998  259  309  324  288  322  326  310  212  115  199  ...    6  260  237   
9999   37  205   86  154   18   33  187  221  346  144  ...  121  163  225   

       16   17   18   19   20   21   22  
0     207   17  107   67   40   22  109  
1     230  197  139  229  310  126  293  
2      68   86  217   67  144   14  105  
3     121    6  352  159  116  286  355  
4     314   35  208  358  270  291  250  
...   ...  ...  ...  ...  ...  ...  ...  
9995   43  247  158  134  230  234  267  
9996  186   58  117    5  219   27  229  
9997  350   81   38    5  248  142  176  
9998  361   68   40   74   38  149   82  
9999  228  102  227   45   59   57  288  

[10000 rows x 23 columns]

In [50]:
# I love nunique, I'm curious what nlargest/nsmallest does in the wild.
(birthdays.nunique(axis=1) < people).mean()

0.4996

In [41]:
people2 = 20
birthdays = np.random.choice(outcome, size=(n_trials,people2))
birthdays = pd.DataFrame(birthdays)
(birthdays.nunique(axis=1) < people2).mean()

0.4164

In [40]:
people3 = 40
birthdays = np.random.choice(outcome, size=(n_trials,people3))
birthdays = pd.DataFrame(birthdays)
(birthdays.nunique(axis=1) < people3).mean()

0.8897